spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/test}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
server:
  virtual-threads:
    enabled: true