// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flights.proto

package com.example.springgrpcvirtualthreads.grpc;

/**
 * Protobuf type {@code flight.FlightsResponse}
 */
public final class FlightsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:flight.FlightsResponse)
    FlightsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FlightsResponse.newBuilder() to construct.
  private FlightsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FlightsResponse() {
    flights_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FlightsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.springgrpcvirtualthreads.grpc.Flights.internal_static_flight_FlightsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.springgrpcvirtualthreads.grpc.Flights.internal_static_flight_FlightsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.springgrpcvirtualthreads.grpc.FlightsResponse.class, com.example.springgrpcvirtualthreads.grpc.FlightsResponse.Builder.class);
  }

  public static final int FLIGHTS_FIELD_NUMBER = 1;
  private java.util.List<com.example.springgrpcvirtualthreads.grpc.Flight> flights_;
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.springgrpcvirtualthreads.grpc.Flight> getFlightsList() {
    return flights_;
  }
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder> 
      getFlightsOrBuilderList() {
    return flights_;
  }
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  @java.lang.Override
  public int getFlightsCount() {
    return flights_.size();
  }
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  @java.lang.Override
  public com.example.springgrpcvirtualthreads.grpc.Flight getFlights(int index) {
    return flights_.get(index);
  }
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  @java.lang.Override
  public com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder getFlightsOrBuilder(
      int index) {
    return flights_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < flights_.size(); i++) {
      output.writeMessage(1, flights_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < flights_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, flights_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.springgrpcvirtualthreads.grpc.FlightsResponse)) {
      return super.equals(obj);
    }
    com.example.springgrpcvirtualthreads.grpc.FlightsResponse other = (com.example.springgrpcvirtualthreads.grpc.FlightsResponse) obj;

    if (!getFlightsList()
        .equals(other.getFlightsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFlightsCount() > 0) {
      hash = (37 * hash) + FLIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + getFlightsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.springgrpcvirtualthreads.grpc.FlightsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flight.FlightsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flight.FlightsResponse)
      com.example.springgrpcvirtualthreads.grpc.FlightsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.springgrpcvirtualthreads.grpc.Flights.internal_static_flight_FlightsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.springgrpcvirtualthreads.grpc.Flights.internal_static_flight_FlightsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.springgrpcvirtualthreads.grpc.FlightsResponse.class, com.example.springgrpcvirtualthreads.grpc.FlightsResponse.Builder.class);
    }

    // Construct using com.example.springgrpcvirtualthreads.grpc.FlightsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (flightsBuilder_ == null) {
        flights_ = java.util.Collections.emptyList();
      } else {
        flights_ = null;
        flightsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.springgrpcvirtualthreads.grpc.Flights.internal_static_flight_FlightsResponse_descriptor;
    }

    @java.lang.Override
    public com.example.springgrpcvirtualthreads.grpc.FlightsResponse getDefaultInstanceForType() {
      return com.example.springgrpcvirtualthreads.grpc.FlightsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.springgrpcvirtualthreads.grpc.FlightsResponse build() {
      com.example.springgrpcvirtualthreads.grpc.FlightsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.springgrpcvirtualthreads.grpc.FlightsResponse buildPartial() {
      com.example.springgrpcvirtualthreads.grpc.FlightsResponse result = new com.example.springgrpcvirtualthreads.grpc.FlightsResponse(this);
      int from_bitField0_ = bitField0_;
      if (flightsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          flights_ = java.util.Collections.unmodifiableList(flights_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.flights_ = flights_;
      } else {
        result.flights_ = flightsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.springgrpcvirtualthreads.grpc.FlightsResponse) {
        return mergeFrom((com.example.springgrpcvirtualthreads.grpc.FlightsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.springgrpcvirtualthreads.grpc.FlightsResponse other) {
      if (other == com.example.springgrpcvirtualthreads.grpc.FlightsResponse.getDefaultInstance()) return this;
      if (flightsBuilder_ == null) {
        if (!other.flights_.isEmpty()) {
          if (flights_.isEmpty()) {
            flights_ = other.flights_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFlightsIsMutable();
            flights_.addAll(other.flights_);
          }
          onChanged();
        }
      } else {
        if (!other.flights_.isEmpty()) {
          if (flightsBuilder_.isEmpty()) {
            flightsBuilder_.dispose();
            flightsBuilder_ = null;
            flights_ = other.flights_;
            bitField0_ = (bitField0_ & ~0x00000001);
            flightsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFlightsFieldBuilder() : null;
          } else {
            flightsBuilder_.addAllMessages(other.flights_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.springgrpcvirtualthreads.grpc.Flight m =
                  input.readMessage(
                      com.example.springgrpcvirtualthreads.grpc.Flight.parser(),
                      extensionRegistry);
              if (flightsBuilder_ == null) {
                ensureFlightsIsMutable();
                flights_.add(m);
              } else {
                flightsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.springgrpcvirtualthreads.grpc.Flight> flights_ =
      java.util.Collections.emptyList();
    private void ensureFlightsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        flights_ = new java.util.ArrayList<com.example.springgrpcvirtualthreads.grpc.Flight>(flights_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.springgrpcvirtualthreads.grpc.Flight, com.example.springgrpcvirtualthreads.grpc.Flight.Builder, com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder> flightsBuilder_;

    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public java.util.List<com.example.springgrpcvirtualthreads.grpc.Flight> getFlightsList() {
      if (flightsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(flights_);
      } else {
        return flightsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public int getFlightsCount() {
      if (flightsBuilder_ == null) {
        return flights_.size();
      } else {
        return flightsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public com.example.springgrpcvirtualthreads.grpc.Flight getFlights(int index) {
      if (flightsBuilder_ == null) {
        return flights_.get(index);
      } else {
        return flightsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder setFlights(
        int index, com.example.springgrpcvirtualthreads.grpc.Flight value) {
      if (flightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlightsIsMutable();
        flights_.set(index, value);
        onChanged();
      } else {
        flightsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder setFlights(
        int index, com.example.springgrpcvirtualthreads.grpc.Flight.Builder builderForValue) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        flights_.set(index, builderForValue.build());
        onChanged();
      } else {
        flightsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder addFlights(com.example.springgrpcvirtualthreads.grpc.Flight value) {
      if (flightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlightsIsMutable();
        flights_.add(value);
        onChanged();
      } else {
        flightsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder addFlights(
        int index, com.example.springgrpcvirtualthreads.grpc.Flight value) {
      if (flightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlightsIsMutable();
        flights_.add(index, value);
        onChanged();
      } else {
        flightsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder addFlights(
        com.example.springgrpcvirtualthreads.grpc.Flight.Builder builderForValue) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        flights_.add(builderForValue.build());
        onChanged();
      } else {
        flightsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder addFlights(
        int index, com.example.springgrpcvirtualthreads.grpc.Flight.Builder builderForValue) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        flights_.add(index, builderForValue.build());
        onChanged();
      } else {
        flightsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder addAllFlights(
        java.lang.Iterable<? extends com.example.springgrpcvirtualthreads.grpc.Flight> values) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, flights_);
        onChanged();
      } else {
        flightsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder clearFlights() {
      if (flightsBuilder_ == null) {
        flights_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        flightsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public Builder removeFlights(int index) {
      if (flightsBuilder_ == null) {
        ensureFlightsIsMutable();
        flights_.remove(index);
        onChanged();
      } else {
        flightsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public com.example.springgrpcvirtualthreads.grpc.Flight.Builder getFlightsBuilder(
        int index) {
      return getFlightsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder getFlightsOrBuilder(
        int index) {
      if (flightsBuilder_ == null) {
        return flights_.get(index);  } else {
        return flightsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public java.util.List<? extends com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder> 
         getFlightsOrBuilderList() {
      if (flightsBuilder_ != null) {
        return flightsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(flights_);
      }
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public com.example.springgrpcvirtualthreads.grpc.Flight.Builder addFlightsBuilder() {
      return getFlightsFieldBuilder().addBuilder(
          com.example.springgrpcvirtualthreads.grpc.Flight.getDefaultInstance());
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public com.example.springgrpcvirtualthreads.grpc.Flight.Builder addFlightsBuilder(
        int index) {
      return getFlightsFieldBuilder().addBuilder(
          index, com.example.springgrpcvirtualthreads.grpc.Flight.getDefaultInstance());
    }
    /**
     * <code>repeated .flight.Flight flights = 1;</code>
     */
    public java.util.List<com.example.springgrpcvirtualthreads.grpc.Flight.Builder> 
         getFlightsBuilderList() {
      return getFlightsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.springgrpcvirtualthreads.grpc.Flight, com.example.springgrpcvirtualthreads.grpc.Flight.Builder, com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder> 
        getFlightsFieldBuilder() {
      if (flightsBuilder_ == null) {
        flightsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.springgrpcvirtualthreads.grpc.Flight, com.example.springgrpcvirtualthreads.grpc.Flight.Builder, com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder>(
                flights_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        flights_ = null;
      }
      return flightsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:flight.FlightsResponse)
  }

  // @@protoc_insertion_point(class_scope:flight.FlightsResponse)
  private static final com.example.springgrpcvirtualthreads.grpc.FlightsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.springgrpcvirtualthreads.grpc.FlightsResponse();
  }

  public static com.example.springgrpcvirtualthreads.grpc.FlightsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FlightsResponse>
      PARSER = new com.google.protobuf.AbstractParser<FlightsResponse>() {
    @java.lang.Override
    public FlightsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FlightsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FlightsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.springgrpcvirtualthreads.grpc.FlightsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

