// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flights.proto

package com.example.springgrpcvirtualthreads.grpc;

public interface FlightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flight.FlightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  java.util.List<com.example.springgrpcvirtualthreads.grpc.Flight> 
      getFlightsList();
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  com.example.springgrpcvirtualthreads.grpc.Flight getFlights(int index);
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  int getFlightsCount();
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  java.util.List<? extends com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder> 
      getFlightsOrBuilderList();
  /**
   * <code>repeated .flight.Flight flights = 1;</code>
   */
  com.example.springgrpcvirtualthreads.grpc.FlightOrBuilder getFlightsOrBuilder(
      int index);
}
